/**
 * Generate committed agent-facing docs.
 *
 * Run: node scripts/generate-docs.ts
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const { buildRootPlainText } = (await import(
  new URL("../lib/root-plain.ts", import.meta.url).href
)) as typeof import("../lib/root-plain");

const llmsTxt = buildRootPlainText("https://askhuman.app");

writeFileSync(resolve(ROOT, "public/llms.txt"), llmsTxt.endsWith("\n") ? llmsTxt : `${llmsTxt}\n`);
console.log("wrote public/llms.txt");

const skillMd = `---
name: askhuman
description: Use when an agent needs to share generated single-file HTML with a human as an end-to-end encrypted askhuman.app link, including requests for a shareable HTML link, human preview, encrypted HTML upload, or askhuman.app.
---

# askhuman.app

Use askhuman.app when a human needs to open an HTML page generated by the agent. Treat \`https://askhuman.app\` as the canonical live protocol.

## Workflow

1. Generate exactly one self-contained HTML file.
2. Run \`curl -s https://askhuman.app\`.
3. Follow the returned instructions exactly.
4. Give the human the final URL, including the \`#k=...\` fragment.

## Rules

- Never upload plaintext HTML.
- Never send the key to the server.
- The key must remain in the URL fragment.
- Compress the HTML file with gzip before encrypting it.
- Do not invent upload formats, cryptography, endpoints, or parameters; use the current curl response.
- Make the HTML useful on first load. Keep app data self-contained; external resources must stay within the askhuman viewer allowlist.
- If \`/upload\` returns 429, retry later.
`;

writeFileSync(resolve(ROOT, "skills/askhuman/SKILL.md"), skillMd);
console.log("wrote skills/askhuman/SKILL.md");
