/**
 * Cloudflare Worker entry point -- auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

export { SessionDO } from "./session";
export { DebugIndexDO } from "./debug-index";

async function handleRootPlain(request: Request): Promise<Response> {
  const base = new URL("/", request.url).toString().replace(/\/$/, "");

  const text = `# askhuman.app

Human-in-the-loop review tools for AI agents.
Submit via curl, open the URL for the user, and poll for the completed review.

## Plan review

  curl -s --data-binary @plan.md ${base}/plan

## Diff review

  curl -s -X POST ${base}/diff \\
    -F description=@description.md \\
    -F diff=@current.diff

## File review

  curl -s -X POST ${base}/files \\
    -F "src/main.ts=<src/main.ts" \\
    -F "src/utils.ts=<src/utils.ts"

## Playground

  curl -s -X POST ${base}/playground \\
    -F "html=<playground.html"

Each response includes a sessionId, a review URL, and polling instructions.
Open the URL for the same user you are already interacting with.
Poll with GET .../{id}/poll -- returns when the user clicks Done.
`;

  return new Response(text.endsWith("\n") ? text : `${text}\n`, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

function handleRootHtml(): Response {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>askhuman.app</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'JetBrains Mono', monospace;
    background: #0c0c0c;
    color: #b0aca6;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 2rem;
  }
  .page { max-width: 560px; width: 100%; }
  h1 { font-size: 2.5rem; color: #e8e4e0; letter-spacing: -0.04em; margin-bottom: 1.5rem; }
  h1 span { font-weight: 400; color: #6b6560; }
  .cmd {
    background: #1a1816;
    border: 1px solid #2a2724;
    border-radius: 6px;
    padding: 1rem 1.25rem;
    margin-bottom: 0.75rem;
    position: relative;
    cursor: pointer;
    transition: border-color 0.15s;
  }
  .cmd:hover { border-color: #4a4540; }
  .cmd pre {
    font-family: inherit; font-size: 0.8125rem;
    line-height: 1.6; white-space: pre-wrap; word-break: break-all;
  }
  .cmd .label {
    font-size: 0.6875rem; color: #6b6560;
    margin-bottom: 0.375rem;
    text-transform: uppercase; letter-spacing: 0.05em;
  }
  .cmd .copy {
    position: absolute; top: 0.75rem; right: 0.75rem;
    font-size: 0.6875rem; color: #6b6560;
    opacity: 0; transition: opacity 0.15s; pointer-events: none;
  }
  .cmd:hover .copy { opacity: 1; }
  .cmd.copied .copy { color: #7a9f6a; }
  .note {
    font-size: 0.6875rem; color: #6b6560;
    margin-top: -0.25rem; margin-bottom: 1.25rem;
  }
  .or {
    text-align: center; font-size: 0.6875rem; color: #4a4540;
    margin: 1rem 0;
    display: flex; align-items: center; gap: 1rem;
  }
  .or::before, .or::after {
    content: ''; flex: 1; height: 1px; background: #2a2724;
  }
  .links {
    font-size: 0.75rem; display: flex; gap: 1.25rem;
    margin-top: 1.5rem; padding-top: 1.25rem;
    border-top: 1px solid #2a2724;
  }
  a { color: #8a8580; text-decoration: underline; text-underline-offset: 2px; transition: color 0.15s; }
  a:hover { color: #e8e4e0; }
</style>
</head>
<body>
<div class="page">
  <h1>askhuman<span>.app</span></h1>

  <div class="cmd" onclick="copyCmd(this, 'npx skills add semistrict/askhuman.app')">
    <div class="label">Install skill</div>
    <pre>npx skills add semistrict/askhuman.app</pre>
    <span class="copy">copy</span>
  </div>

  <div class="or">or</div>

  <div class="cmd" onclick="copyCmd(this, 'claude &quot;$(curl -s https://askhuman.app) -- review my current diff&quot;')">
    <div class="label">Prompt-inject yourself</div>
    <pre>claude "$(curl -s https://askhuman.app) -- review my current diff"</pre>
    <span class="copy">copy</span>
  </div>
  <p class="note">Works with any agent that accepts a prompt string.</p>

  <div class="links">
    <a href="https://github.com/semistrict/askhuman.app">github</a>
    <a href="/llms.txt">llms.txt</a>
  </div>
</div>
<script>
function copyCmd(el, text) {
  navigator.clipboard.writeText(text.replace(/\\\\n/g, '\\n'));
  var span = el.querySelector('.copy');
  span.textContent = 'copied';
  el.classList.add('copied');
  setTimeout(() => { el.classList.remove('copied'); span.textContent = 'copy'; }, 1500);
}
</script>
</body>
</html>`;

  return new Response(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}


interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  SESSION: DurableObjectNamespace;
  DEBUG_INDEX: DurableObjectNamespace;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // https://askhuman.app -> instructions (plain text for curl, HTML for browsers)
    if (url.pathname === "/" && request.method === "GET") {
      const ua = request.headers.get("user-agent") || "";
      if (/^curl\//i.test(ua)) {
        return handleRootPlain(request);
      }
      return handleRootHtml();
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    return handler.fetch(request, env, ctx);
  },
};
