/**
 * Cloudflare Worker entry point -- auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";
import { buildRootPlainText, detectRootPlainRecipe } from "@/lib/root-plain";

async function handleRootPlain(request: Request): Promise<Response> {
  const base = new URL("/", request.url).toString().replace(/\/$/, "");
  const text = buildRootPlainText(base, { recipe: detectRootPlainRecipe(request) });

  return new Response(text.endsWith("\n") ? text : `${text}\n`, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

function shouldServePlainRoot(request: Request): boolean {
  const userAgent = request.headers.get("user-agent") || "";
  const signatureAgent = request.headers.get("signature-agent") || "";

  if (/^curl\//i.test(userAgent)) return true;
  if (detectRootPlainRecipe(request) === "powershell") return true;
  if (signatureAgent.trim() === "https://chatgpt.com") return true;
  if (/\bClaude-User\b/i.test(userAgent)) return true;
  if (/\bChatGPT-User\b/i.test(userAgent)) return true;

  return false;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface Env {
  ASSETS: Fetcher;
  SHARE_KEYS: KVNamespace;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

const worker = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    if (url.pathname === "/llms.txt" && request.method === "GET") {
      return handleRootPlain(request);
    }

    // https://askhuman.app -> instructions (plain text for curl, HTML for browsers)
    if (url.pathname === "/" && request.method === "GET") {
      if (shouldServePlainRoot(request)) {
        return handleRootPlain(request);
      }
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    return handler.fetch(request, env, ctx);
  },
};

export default worker;
