/**
 * Cloudflare Worker entry point -- auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

export { SessionDO } from "./session";
export { DebugIndexDO } from "./debug-index";

async function handleRootPlain(request: Request): Promise<Response> {
  const base = new URL("/", request.url).toString().replace(/\/$/, "");

  const text = `askhuman.app -- human-in-the-loop review tools for AI agents

Use this with the same user you are already interacting with. After you submit, open the returned review URL in that user's browser.

1. Write your plan to a file, then post it:

  curl -s --data-binary @plan.md ${base}/plan

2. Or submit a diff for review:

  curl -s -X POST ${base}/diff \\
    -F description=@description.md \\
    -F diff=@current.diff

3. Or submit files for review:

  curl -s -X POST ${base}/files \\
    -F "src/main.ts=<src/main.ts" \\
    -F "src/utils.ts=<src/utils.ts"

Response includes sessionId, review URL, and instructions for polling and replying.
`;

  return new Response(text.endsWith("\n") ? text : `${text}\n`, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}

function handleRootHtml(): Response {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>askhuman.app</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'JetBrains Mono', monospace;
    background: #0c0c0c;
    color: #b0aca6;
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 2rem;
  }
  .page { max-width: 560px; width: 100%; }
  h1 { font-size: 2.5rem; color: #e8e4e0; letter-spacing: -0.04em; margin-bottom: 1.5rem; }
  h1 span { font-weight: 400; color: #6b6560; }
  .hero {
    background: #1a1816;
    border: 1px solid #2a2724;
    border-radius: 6px;
    padding: 0.75rem 1rem;
    margin-bottom: 1.25rem;
    position: relative;
    cursor: pointer;
    transition: border-color 0.15s;
  }
  .hero:hover { border-color: #4a4540; }
  .hero pre { font-family: inherit; font-size: 0.8125rem; line-height: 1.6; }
  .hero .copy {
    position: absolute; top: 0.6rem; right: 0.75rem;
    font-size: 0.6875rem; color: #6b6560;
    opacity: 0; transition: opacity 0.15s; pointer-events: none;
  }
  .hero:hover .copy { opacity: 1; }
  .hero.copied .copy { color: #7a9f6a; }
  .hero-note { font-size: 0.6875rem; color: #6b6560; margin-bottom: 1.5rem; }
  .tabs {
    display: flex; gap: 0;
    border-bottom: 1px solid #2a2724;
    margin-bottom: 0;
  }
  .tab {
    flex: 1; padding: 0.5rem 0; text-align: center;
    font-family: inherit; font-size: 0.6875rem; font-weight: 400;
    color: #6b6560; background: none; border: none;
    cursor: pointer; transition: color 0.15s;
    letter-spacing: 0.03em; text-transform: uppercase;
    border-bottom: 2px solid transparent;
    margin-bottom: -1px;
  }
  .tab:hover { color: #b0aca6; }
  .tab.active { color: #e8e4e0; border-bottom-color: #e8e4e0; }
  .panel {
    display: none;
    background: #1a1816;
    border: 1px solid #2a2724;
    border-top: none;
    border-radius: 0 0 6px 6px;
    padding: 1rem 1.25rem;
    position: relative;
    cursor: pointer;
    transition: border-color 0.15s;
  }
  .panel.active { display: block; }
  .panel:hover { border-color: #4a4540; }
  .panel pre {
    font-family: inherit; font-size: 0.8125rem;
    line-height: 1.6; white-space: pre-wrap; word-break: break-all;
  }
  .panel .copy {
    position: absolute; top: 0.75rem; right: 0.75rem;
    font-size: 0.6875rem; color: #6b6560;
    opacity: 0; transition: opacity 0.15s; pointer-events: none;
  }
  .panel:hover .copy { opacity: 1; }
  .panel.copied .copy { color: #7a9f6a; }
  .panel-note {
    font-size: 0.6875rem; color: #6b6560;
    margin-top: 0.75rem; padding-top: 0.75rem;
    border-top: 1px solid #2a2724;
  }
  .links {
    font-size: 0.75rem; display: flex; gap: 1.25rem;
    margin-top: 1.5rem; padding-top: 1.25rem;
    border-top: 1px solid #2a2724;
  }
  a { color: #8a8580; text-decoration: underline; text-underline-offset: 2px; transition: color 0.15s; }
  a:hover { color: #e8e4e0; }
</style>
</head>
<body>
<div class="page">
  <h1>askhuman<span>.app</span></h1>

  <div class="hero" onclick="copyCmd(this, 'curl -s https://askhuman.app')">
    <pre>curl -s https://askhuman.app</pre>
    <span class="copy">copy</span>
  </div>
  <p class="hero-note">Detects your agent and prints session-specific instructions.</p>

  <div class="tabs">
    <button class="tab active" onclick="showTab('diff')">diff</button>
    <button class="tab" onclick="showTab('plan')">plan</button>
    <button class="tab" onclick="showTab('files')">files</button>
    <button class="tab" onclick="showTab('playground')">playground</button>
  </div>

  <div class="panel active" id="tab-diff" onclick="copyCmd(this, 'curl -s -X POST https://askhuman.app/diff -F description=@description.md -F diff=@current.diff')">
    <pre>curl -s -X POST https://askhuman.app/diff \\
  -F description=@description.md \\
  -F diff=@current.diff</pre>
    <span class="copy">copy</span>
    <p class="panel-note">Narrated diff review with inline hunks and a table of contents.</p>
  </div>

  <div class="panel" id="tab-plan" onclick="copyCmd(this, 'curl -s --data-binary @plan.md https://askhuman.app/plan')">
    <pre>curl -s --data-binary @plan.md \\
  https://askhuman.app/plan</pre>
    <span class="copy">copy</span>
    <p class="panel-note">Line-by-line markdown review with numbered comments.</p>
  </div>

  <div class="panel" id="tab-files" onclick="copyCmd(this, 'curl -s -X POST https://askhuman.app/files -F &quot;src/main.ts=<src/main.ts&quot;')">
    <pre>curl -s -X POST https://askhuman.app/files \\
  -F "src/main.ts=<src/main.ts" \\
  -F "src/utils.ts=<src/utils.ts"</pre>
    <span class="copy">copy</span>
    <p class="panel-note">File selector with syntax highlighting. Field name = path, value = content.</p>
  </div>

  <div class="panel" id="tab-playground" onclick="copyCmd(this, 'curl -s -X POST https://askhuman.app/playground -F &quot;html=<playground.html&quot;')">
    <pre>curl -s -X POST https://askhuman.app/playground \\
  -F "html=<playground.html"</pre>
    <span class="copy">copy</span>
    <p class="panel-note">Any self-contained HTML. Results via postMessage. User interacts, clicks Done.</p>
  </div>

  <div class="links">
    <a href="https://github.com/semistrict/askhuman.app">github</a>
    <a href="/llms.txt">llms.txt</a>
  </div>
</div>
<script>
function showTab(name) {
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  event.target.classList.add('active');
  document.getElementById('tab-' + name).classList.add('active');
}
function copyCmd(el, text) {
  navigator.clipboard.writeText(text.replace(/\\\\n/g, '\\n'));
  var span = el.querySelector('.copy');
  span.textContent = 'copied';
  el.classList.add('copied');
  setTimeout(() => { el.classList.remove('copied'); span.textContent = 'copy'; }, 1500);
}
</script>
</body>
</html>`;

  return new Response(html, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}


interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  SESSION: DurableObjectNamespace;
  DEBUG_INDEX: DurableObjectNamespace;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // https://askhuman.app -> instructions (plain text for curl, HTML for browsers)
    if (url.pathname === "/" && request.method === "GET") {
      const ua = request.headers.get("user-agent") || "";
      if (/^curl\//i.test(ua)) {
        return handleRootPlain(request);
      }
      return handleRootHtml();
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    return handler.fetch(request, env, ctx);
  },
};
