/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as BookmarkletDotjsRouteImport } from './routes/bookmarklet[.]js'
import { Route as BookmarkletReceiverRouteImport } from './routes/bookmarklet-receiver'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SIdRouteImport } from './routes/s/$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarkletDotjsRoute = BookmarkletDotjsRouteImport.update({
  id: '/bookmarklet.js',
  path: '/bookmarklet.js',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarkletReceiverRoute = BookmarkletReceiverRouteImport.update({
  id: '/bookmarklet-receiver',
  path: '/bookmarklet-receiver',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarklet-receiver': typeof BookmarkletReceiverRoute
  '/bookmarklet.js': typeof BookmarkletDotjsRoute
  '/upload': typeof UploadRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarklet-receiver': typeof BookmarkletReceiverRoute
  '/bookmarklet.js': typeof BookmarkletDotjsRoute
  '/upload': typeof UploadRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarklet-receiver': typeof BookmarkletReceiverRoute
  '/bookmarklet.js': typeof BookmarkletDotjsRoute
  '/upload': typeof UploadRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarklet-receiver'
    | '/bookmarklet.js'
    | '/upload'
    | '/s/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bookmarklet-receiver' | '/bookmarklet.js' | '/upload' | '/s/$id'
  id:
    | '__root__'
    | '/'
    | '/bookmarklet-receiver'
    | '/bookmarklet.js'
    | '/upload'
    | '/s/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarkletReceiverRoute: typeof BookmarkletReceiverRoute
  BookmarkletDotjsRoute: typeof BookmarkletDotjsRoute
  UploadRoute: typeof UploadRoute
  SIdRoute: typeof SIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarklet.js': {
      id: '/bookmarklet.js'
      path: '/bookmarklet.js'
      fullPath: '/bookmarklet.js'
      preLoaderRoute: typeof BookmarkletDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarklet-receiver': {
      id: '/bookmarklet-receiver'
      path: '/bookmarklet-receiver'
      fullPath: '/bookmarklet-receiver'
      preLoaderRoute: typeof BookmarkletReceiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarkletReceiverRoute: BookmarkletReceiverRoute,
  BookmarkletDotjsRoute: BookmarkletDotjsRoute,
  UploadRoute: UploadRoute,
  SIdRoute: SIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
